services:
  mongo:
    image: mongo:7
    container_name: structured-products-mongo
    ports:
      - "27017:27017"
    volumes:
      - structured-products-mongo-data:/data/db
    restart: unless-stopped

volumes:
  structured-products-mongo-data:
