package com.contactfirstio.structuredproducts.catalog

import com.contactfirstio.structuredproducts.data.document.FieldDataType
import com.contactfirstio.structuredproducts.data.document.FieldKind
import com.contactfirstio.structuredproducts.data.document.FieldRequirement

object CommonFieldCatalog {

  const val CATEGORY_COUNTERPARTY_AND_TENOR = "Counterparty & Tenor"
  const val CATEGORY_MONETARY_AND_SIZE = "Monetary & Size"
  const val CATEGORY_COUPON_STRUCTURE = "Coupon Structure"
  const val CATEGORY_BARRIERS_AND_LEVELS = "Barriers & Levels"
  const val CATEGORY_MARKET_AND_TECHNICAL = "Market & Technical"

  val fields: List<CatalogFieldDefinition> =
      listOf(
          field(
              key = "counterparty_by_rating_option",
              category = CATEGORY_COUNTERPARTY_AND_TENOR,
              displayName = "CounterParty (By Rating) - Option",
              dataType = FieldDataType.STRING,
              requirement = FieldRequirement.MANDATORY,
              enumOptions = listOf("Required", "Not Required", "Optional"),
          ),
          field(
              key = "counterparty_by_rating_in_email_conf",
              category = CATEGORY_COUNTERPARTY_AND_TENOR,
              displayName = "CounterParty (By Rating) - In email conf",
              dataType = FieldDataType.BOOLEAN,
              requirement = FieldRequirement.OPTIONAL,
              enumOptions = listOf("True", "False"),
          ),
          field(
              key = "counterparty_by_rating_bex_logic",
              category = CATEGORY_COUNTERPARTY_AND_TENOR,
              displayName = "CounterParty (By Rating) - BEX Logic",
              dataType = FieldDataType.STRING,
              requirement = FieldRequirement.MANDATORY,
              enumOptions = listOf("N/A", "Auto-Generate", "Manual Entry", "System Override"),
          ),
          field(
              key = "counterparty_by_rating",
              category = CATEGORY_COUNTERPARTY_AND_TENOR,
              displayName = "CounterParty (By Rating)",
              dataType = FieldDataType.STRING,
              requirement = FieldRequirement.OPTIONAL,
              enumOptions = listOf("AAA", "AA", "A", "BBB", "BB", "B", "Unrated"),
          ),
          field(
              key = "settlement_period_option",
              category = CATEGORY_COUNTERPARTY_AND_TENOR,
              displayName = "Settlement Period - Option",
              dataType = FieldDataType.STRING,
              requirement = FieldRequirement.MANDATORY,
              enumOptions = listOf("Required", "Not Required", "Optional"),
          ),
          field(
              key = "settlement_period_in_email_conf",
              category = CATEGORY_COUNTERPARTY_AND_TENOR,
              displayName = "Settlement Period - In email conf",
              dataType = FieldDataType.BOOLEAN,
              requirement = FieldRequirement.OPTIONAL,
              enumOptions = listOf("True", "False"),
          ),
          field(
              key = "settlement_period_bex_logic",
              category = CATEGORY_COUNTERPARTY_AND_TENOR,
              displayName = "Settlement Period - BEX Logic",
              dataType = FieldDataType.STRING,
              requirement = FieldRequirement.MANDATORY,
              enumOptions = listOf("N/A", "Auto-Generate", "Manual Entry", "System Override"),
          ),
          field(
              key = "settlement_period",
              category = CATEGORY_COUNTERPARTY_AND_TENOR,
              displayName = "Settlement Period",
              dataType = FieldDataType.STRING,
              requirement = FieldRequirement.OPTIONAL,
              enumOptions = listOf("T+0", "T+1", "T+2"),
          ),
          field(
              key = "tenor_option",
              category = CATEGORY_COUNTERPARTY_AND_TENOR,
              displayName = "Tenor - Option",
              dataType = FieldDataType.STRING,
              requirement = FieldRequirement.MANDATORY,
              enumOptions = listOf("Required", "Not Required", "Optional"),
          ),
          field(
              key = "tenor_in_email_conf",
              category = CATEGORY_COUNTERPARTY_AND_TENOR,
              displayName = "Tenor - In email conf",
              dataType = FieldDataType.BOOLEAN,
              requirement = FieldRequirement.OPTIONAL,
              enumOptions = listOf("True", "False"),
          ),
          field(
              key = "tenor_bex_logic",
              category = CATEGORY_COUNTERPARTY_AND_TENOR,
              displayName = "Tenor - BEX Logic",
              dataType = FieldDataType.STRING,
              requirement = FieldRequirement.MANDATORY,
              enumOptions = listOf("N/A", "Auto-Generate", "Manual Entry", "System Override"),
          ),
          field(
              key = "tenor",
              category = CATEGORY_COUNTERPARTY_AND_TENOR,
              displayName = "Tenor",
              dataType = FieldDataType.STRING,
              requirement = FieldRequirement.OPTIONAL,
              enumOptions = listOf("1 Week", "1 Month", "3 Months", "6 Months", "1 Year"),
          ),
          field(
              key = "issuer_option",
              category = CATEGORY_COUNTERPARTY_AND_TENOR,
              displayName = "Issuer - Option",
              dataType = FieldDataType.STRING,
              requirement = FieldRequirement.MANDATORY,
              enumOptions = listOf("Required", "Not Required", "Optional"),
          ),
          field(
              key = "issuer_in_email_conf",
              category = CATEGORY_COUNTERPARTY_AND_TENOR,
              displayName = "Issuer - In email conf",
              dataType = FieldDataType.BOOLEAN,
              requirement = FieldRequirement.OPTIONAL,
              enumOptions = listOf("True", "False"),
          ),
          field(
              key = "issuer_bex_logic",
              category = CATEGORY_COUNTERPARTY_AND_TENOR,
              displayName = "Issuer - BEX Logic",
              dataType = FieldDataType.STRING,
              requirement = FieldRequirement.MANDATORY,
              enumOptions = listOf("N/A", "Auto-Generate", "Manual Entry", "System Override"),
          ),
          field(
              key = "issuer",
              category = CATEGORY_COUNTERPARTY_AND_TENOR,
              displayName = "Issuer",
              dataType = FieldDataType.STRING,
              requirement = FieldRequirement.OPTIONAL,
          ),
          field(
              key = "counterparty_option",
              category = CATEGORY_COUNTERPARTY_AND_TENOR,
              displayName = "Counterparty - Option",
              dataType = FieldDataType.STRING,
              requirement = FieldRequirement.MANDATORY,
              enumOptions = listOf("Required", "Not Required", "Optional"),
          ),
          field(
              key = "counterparty_in_email_conf",
              category = CATEGORY_COUNTERPARTY_AND_TENOR,
              displayName = "Counterparty - In email conf",
              dataType = FieldDataType.BOOLEAN,
              requirement = FieldRequirement.OPTIONAL,
              enumOptions = listOf("True", "False"),
          ),
          field(
              key = "counterparty_bex_logic",
              category = CATEGORY_COUNTERPARTY_AND_TENOR,
              displayName = "Counterparty - BEX Logic",
              dataType = FieldDataType.STRING,
              requirement = FieldRequirement.MANDATORY,
              enumOptions = listOf("N/A", "Auto-Generate", "Manual Entry", "System Override"),
          ),
          field(
              key = "counterparty",
              category = CATEGORY_COUNTERPARTY_AND_TENOR,
              displayName = "Counterparty",
              dataType = FieldDataType.STRING,
              requirement = FieldRequirement.OPTIONAL,
          ),
          field(
              key = "currency_option",
              category = CATEGORY_MONETARY_AND_SIZE,
              displayName = "Currency - Option",
              dataType = FieldDataType.STRING,
              requirement = FieldRequirement.MANDATORY,
              enumOptions = listOf("Required", "Not Required", "Optional"),
          ),
          field(
              key = "currency_in_email_conf",
              category = CATEGORY_MONETARY_AND_SIZE,
              displayName = "Currency - In email conf",
              dataType = FieldDataType.BOOLEAN,
              requirement = FieldRequirement.OPTIONAL,
              enumOptions = listOf("True", "False"),
          ),
          field(
              key = "currency_bex_logic",
              category = CATEGORY_MONETARY_AND_SIZE,
              displayName = "Currency - BEX Logic",
              dataType = FieldDataType.STRING,
              requirement = FieldRequirement.MANDATORY,
              enumOptions = listOf("N/A", "Auto-Generate", "Manual Entry", "System Override"),
          ),
          field(
              key = "currency",
              category = CATEGORY_MONETARY_AND_SIZE,
              displayName = "Currency",
              dataType = FieldDataType.STRING,
              requirement = FieldRequirement.OPTIONAL,
              enumOptions = listOf("USD", "HKD", "GBP", "EUR", "JPY"),
          ),
          field(
              key = "size_option",
              category = CATEGORY_MONETARY_AND_SIZE,
              displayName = "Size - Option",
              dataType = FieldDataType.STRING,
              requirement = FieldRequirement.MANDATORY,
              enumOptions = listOf("Required", "Not Required", "Optional"),
          ),
          field(
              key = "size_in_email_conf",
              category = CATEGORY_MONETARY_AND_SIZE,
              displayName = "Size - In email conf",
              dataType = FieldDataType.BOOLEAN,
              requirement = FieldRequirement.OPTIONAL,
              enumOptions = listOf("True", "False"),
          ),
          field(
              key = "size_bex_logic",
              category = CATEGORY_MONETARY_AND_SIZE,
              displayName = "Size - BEX Logic",
              dataType = FieldDataType.STRING,
              requirement = FieldRequirement.MANDATORY,
              enumOptions = listOf("N/A", "Auto-Generate", "Manual Entry", "System Override"),
          ),
          field(
              key = "size",
              category = CATEGORY_MONETARY_AND_SIZE,
              displayName = "Size",
              dataType = FieldDataType.STRING,
              requirement = FieldRequirement.OPTIONAL,
          ),
          field(
              key = "ib_price_pct_option",
              category = CATEGORY_MONETARY_AND_SIZE,
              displayName = "IB Price(%) - Option",
              dataType = FieldDataType.STRING,
              requirement = FieldRequirement.MANDATORY,
              enumOptions = listOf("Required", "Not Required", "Optional"),
          ),
          field(
              key = "ib_price_pct_in_email_conf",
              category = CATEGORY_MONETARY_AND_SIZE,
              displayName = "IB Price(%) - In email conf",
              dataType = FieldDataType.BOOLEAN,
              requirement = FieldRequirement.OPTIONAL,
              enumOptions = listOf("True", "False"),
          ),
          field(
              key = "ib_price_pct_bex_logic",
              category = CATEGORY_MONETARY_AND_SIZE,
              displayName = "IB Price(%) - BEX Logic",
              dataType = FieldDataType.STRING,
              requirement = FieldRequirement.MANDATORY,
              enumOptions = listOf("N/A", "Auto-Generate", "Manual Entry", "System Override"),
          ),
          field(
              key = "ib_price_pct",
              category = CATEGORY_MONETARY_AND_SIZE,
              displayName = "IB Price(%)",
              dataType = FieldDataType.DOUBLE,
              requirement = FieldRequirement.OPTIONAL,
          ),
          field(
              key = "fixed_coupon_pa_pct_option",
              category = CATEGORY_COUPON_STRUCTURE,
              displayName = "Fixed Coupon (p.a.) (%) - Option",
              dataType = FieldDataType.STRING,
              requirement = FieldRequirement.MANDATORY,
              enumOptions = listOf("Required", "Not Required", "Optional"),
          ),
          field(
              key = "fixed_coupon_pa_pct_in_email_conf",
              category = CATEGORY_COUPON_STRUCTURE,
              displayName = "Fixed Coupon (p.a.) (%) - In email conf",
              dataType = FieldDataType.BOOLEAN,
              requirement = FieldRequirement.OPTIONAL,
              enumOptions = listOf("True", "False"),
          ),
          field(
              key = "fixed_coupon_pa_pct_bex_logic",
              category = CATEGORY_COUPON_STRUCTURE,
              displayName = "Fixed Coupon (p.a.) (%) - BEX Logic",
              dataType = FieldDataType.STRING,
              requirement = FieldRequirement.MANDATORY,
              enumOptions = listOf("N/A", "Auto-Generate", "Manual Entry", "System Override"),
          ),
          field(
              key = "fixed_coupon_pa_pct",
              category = CATEGORY_COUPON_STRUCTURE,
              displayName = "Fixed Coupon (p.a.) (%)",
              dataType = FieldDataType.DOUBLE,
              requirement = FieldRequirement.OPTIONAL,
          ),
          field(
              key = "bonus_coupon_pa_pct_option",
              category = CATEGORY_COUPON_STRUCTURE,
              displayName = "Bonus Coupon (p.a.) (%) - Option",
              dataType = FieldDataType.STRING,
              requirement = FieldRequirement.MANDATORY,
              enumOptions = listOf("Required", "Not Required", "Optional"),
          ),
          field(
              key = "bonus_coupon_pa_pct_in_email_conf",
              category = CATEGORY_COUPON_STRUCTURE,
              displayName = "Bonus Coupon (p.a.) (%) - In email conf",
              dataType = FieldDataType.BOOLEAN,
              requirement = FieldRequirement.OPTIONAL,
              enumOptions = listOf("True", "False"),
          ),
          field(
              key = "bonus_coupon_pa_pct_bex_logic",
              category = CATEGORY_COUPON_STRUCTURE,
              displayName = "Bonus Coupon (p.a.) (%) - BEX Logic",
              dataType = FieldDataType.STRING,
              requirement = FieldRequirement.MANDATORY,
              enumOptions = listOf("N/A", "Auto-Generate", "Manual Entry", "System Override"),
          ),
          field(
              key = "bonus_coupon_pa_pct",
              category = CATEGORY_COUPON_STRUCTURE,
              displayName = "Bonus Coupon (p.a.) (%)",
              dataType = FieldDataType.DOUBLE,
              requirement = FieldRequirement.OPTIONAL,
          ),
          field(
              key = "variable_coupon_pa_pct_option",
              category = CATEGORY_COUPON_STRUCTURE,
              displayName = "Variable Coupon (p.a.) (%) - Option",
              dataType = FieldDataType.STRING,
              requirement = FieldRequirement.MANDATORY,
              enumOptions = listOf("Required", "Not Required", "Optional"),
          ),
          field(
              key = "variable_coupon_pa_pct_in_email_conf",
              category = CATEGORY_COUPON_STRUCTURE,
              displayName = "Variable Coupon (p.a.) (%) - In email conf",
              dataType = FieldDataType.BOOLEAN,
              requirement = FieldRequirement.OPTIONAL,
              enumOptions = listOf("True", "False"),
          ),
          field(
              key = "variable_coupon_pa_pct_bex_logic",
              category = CATEGORY_COUPON_STRUCTURE,
              displayName = "Variable Coupon (p.a.) (%) - BEX Logic",
              dataType = FieldDataType.STRING,
              requirement = FieldRequirement.MANDATORY,
              enumOptions = listOf("N/A", "Auto-Generate", "Manual Entry", "System Override"),
          ),
          field(
              key = "variable_coupon_pa_pct",
              category = CATEGORY_COUPON_STRUCTURE,
              displayName = "Variable Coupon (p.a.) (%)",
              dataType = FieldDataType.DOUBLE,
              requirement = FieldRequirement.OPTIONAL,
          ),
          field(
              key = "min_coupon_pa_pct_option",
              category = CATEGORY_COUPON_STRUCTURE,
              displayName = "Min. Coupon (p.a.) (%) - Option",
              dataType = FieldDataType.STRING,
              requirement = FieldRequirement.MANDATORY,
              enumOptions = listOf("Required", "Not Required", "Optional"),
          ),
          field(
              key = "min_coupon_pa_pct_in_email_conf",
              category = CATEGORY_COUPON_STRUCTURE,
              displayName = "Min. Coupon (p.a.) (%) - In email conf",
              dataType = FieldDataType.BOOLEAN,
              requirement = FieldRequirement.OPTIONAL,
              enumOptions = listOf("True", "False"),
          ),
          field(
              key = "min_coupon_pa_pct_bex_logic",
              category = CATEGORY_COUPON_STRUCTURE,
              displayName = "Min. Coupon (p.a.) (%) - BEX Logic",
              dataType = FieldDataType.STRING,
              requirement = FieldRequirement.MANDATORY,
              enumOptions = listOf("N/A", "Auto-Generate", "Manual Entry", "System Override"),
          ),
          field(
              key = "min_coupon_pa_pct",
              category = CATEGORY_COUPON_STRUCTURE,
              displayName = "Min. Coupon (p.a.) (%)",
              dataType = FieldDataType.DOUBLE,
              requirement = FieldRequirement.OPTIONAL,
          ),
          field(
              key = "max_coupon_pa_pct_option",
              category = CATEGORY_COUPON_STRUCTURE,
              displayName = "Max. Coupon (p.a.) (%) - Option",
              dataType = FieldDataType.STRING,
              requirement = FieldRequirement.MANDATORY,
              enumOptions = listOf("Required", "Not Required", "Optional"),
          ),
          field(
              key = "max_coupon_pa_pct_in_email_conf",
              category = CATEGORY_COUPON_STRUCTURE,
              displayName = "Max. Coupon (p.a.) (%) - In email conf",
              dataType = FieldDataType.BOOLEAN,
              requirement = FieldRequirement.OPTIONAL,
              enumOptions = listOf("True", "False"),
          ),
          field(
              key = "max_coupon_pa_pct_bex_logic",
              category = CATEGORY_COUPON_STRUCTURE,
              displayName = "Max. Coupon (p.a.) (%) - BEX Logic",
              dataType = FieldDataType.STRING,
              requirement = FieldRequirement.MANDATORY,
              enumOptions = listOf("N/A", "Auto-Generate", "Manual Entry", "System Override"),
          ),
          field(
              key = "max_coupon_pa_pct",
              category = CATEGORY_COUPON_STRUCTURE,
              displayName = "Max. Coupon (p.a.) (%)",
              dataType = FieldDataType.DOUBLE,
              requirement = FieldRequirement.OPTIONAL,
          ),
          field(
              key = "head_start_coupon_pa_pct_option",
              category = CATEGORY_COUPON_STRUCTURE,
              displayName = "Head-Start Coupon (p.a.) (%) - Option",
              dataType = FieldDataType.STRING,
              requirement = FieldRequirement.MANDATORY,
              enumOptions = listOf("Required", "Not Required", "Optional"),
          ),
          field(
              key = "head_start_coupon_pa_pct_in_email_conf",
              category = CATEGORY_COUPON_STRUCTURE,
              displayName = "Head-Start Coupon (p.a.) (%) - In email conf",
              dataType = FieldDataType.BOOLEAN,
              requirement = FieldRequirement.OPTIONAL,
              enumOptions = listOf("True", "False"),
          ),
          field(
              key = "head_start_coupon_pa_pct_bex_logic",
              category = CATEGORY_COUPON_STRUCTURE,
              displayName = "Head-Start Coupon (p.a.) (%) - BEX Logic",
              dataType = FieldDataType.STRING,
              requirement = FieldRequirement.MANDATORY,
              enumOptions = listOf("N/A", "Auto-Generate", "Manual Entry", "System Override"),
          ),
          field(
              key = "head_start_coupon_pa_pct",
              category = CATEGORY_COUPON_STRUCTURE,
              displayName = "Head-Start Coupon (p.a.) (%)",
              dataType = FieldDataType.DOUBLE,
              requirement = FieldRequirement.OPTIONAL,
          ),
          field(
              key = "target_coupon_pa_pct_option",
              category = CATEGORY_COUPON_STRUCTURE,
              displayName = "Target Coupon (p.a.) (%) - Option",
              dataType = FieldDataType.STRING,
              requirement = FieldRequirement.MANDATORY,
              enumOptions = listOf("Required", "Not Required", "Optional"),
          ),
          field(
              key = "target_coupon_pa_pct_in_email_conf",
              category = CATEGORY_COUPON_STRUCTURE,
              displayName = "Target Coupon (p.a.) (%) - In email conf",
              dataType = FieldDataType.BOOLEAN,
              requirement = FieldRequirement.OPTIONAL,
              enumOptions = listOf("True", "False"),
          ),
          field(
              key = "target_coupon_pa_pct_bex_logic",
              category = CATEGORY_COUPON_STRUCTURE,
              displayName = "Target Coupon (p.a.) (%) - BEX Logic",
              dataType = FieldDataType.STRING,
              requirement = FieldRequirement.MANDATORY,
              enumOptions = listOf("N/A", "Auto-Generate", "Manual Entry", "System Override"),
          ),
          field(
              key = "target_coupon_pa_pct",
              category = CATEGORY_COUPON_STRUCTURE,
              displayName = "Target Coupon (p.a.) (%)",
              dataType = FieldDataType.DOUBLE,
              requirement = FieldRequirement.OPTIONAL,
          ),
          field(
              key = "no_of_fixed_coupon_period_option",
              category = CATEGORY_COUPON_STRUCTURE,
              displayName = "No. of Fixed Coupon Period - Option",
              dataType = FieldDataType.STRING,
              requirement = FieldRequirement.MANDATORY,
              enumOptions = listOf("Required", "Not Required", "Optional"),
          ),
          field(
              key = "no_of_fixed_coupon_period_in_email_conf",
              category = CATEGORY_COUPON_STRUCTURE,
              displayName = "No. of Fixed Coupon Period - In email conf",
              dataType = FieldDataType.BOOLEAN,
              requirement = FieldRequirement.OPTIONAL,
              enumOptions = listOf("True", "False"),
          ),
          field(
              key = "no_of_fixed_coupon_period_bex_logic",
              category = CATEGORY_COUPON_STRUCTURE,
              displayName = "No. of Fixed Coupon Period - BEX Logic",
              dataType = FieldDataType.STRING,
              requirement = FieldRequirement.MANDATORY,
              enumOptions = listOf("N/A", "Auto-Generate", "Manual Entry", "System Override"),
          ),
          field(
              key = "no_of_fixed_coupon_period",
              category = CATEGORY_COUPON_STRUCTURE,
              displayName = "No. of Fixed Coupon Period",
              dataType = FieldDataType.STRING,
              requirement = FieldRequirement.OPTIONAL,
          ),
          field(
              key = "cpn_pa_pct_option",
              category = CATEGORY_COUPON_STRUCTURE,
              displayName = "Cpn p.a. (%) - Option",
              dataType = FieldDataType.STRING,
              requirement = FieldRequirement.MANDATORY,
              enumOptions = listOf("Required", "Not Required", "Optional"),
          ),
          field(
              key = "cpn_pa_pct_in_email_conf",
              category = CATEGORY_COUPON_STRUCTURE,
              displayName = "Cpn p.a. (%) - In email conf",
              dataType = FieldDataType.BOOLEAN,
              requirement = FieldRequirement.OPTIONAL,
              enumOptions = listOf("True", "False"),
          ),
          field(
              key = "cpn_pa_pct_bex_logic",
              category = CATEGORY_COUPON_STRUCTURE,
              displayName = "Cpn p.a. (%) - BEX Logic",
              dataType = FieldDataType.STRING,
              requirement = FieldRequirement.MANDATORY,
              enumOptions = listOf("N/A", "Auto-Generate", "Manual Entry", "System Override"),
          ),
          field(
              key = "cpn_pa_pct",
              category = CATEGORY_COUPON_STRUCTURE,
              displayName = "Cpn p.a. (%)",
              dataType = FieldDataType.DOUBLE,
              requirement = FieldRequirement.OPTIONAL,
          ),
          field(
              key = "step_up_coupon_pa_pct_option",
              category = CATEGORY_COUPON_STRUCTURE,
              displayName = "Step-up Coupon (p.a.) (%) - Option",
              dataType = FieldDataType.STRING,
              requirement = FieldRequirement.MANDATORY,
              enumOptions = listOf("Required", "Not Required", "Optional"),
          ),
          field(
              key = "step_up_coupon_pa_pct_in_email_conf",
              category = CATEGORY_COUPON_STRUCTURE,
              displayName = "Step-up Coupon (p.a.) (%) - In email conf",
              dataType = FieldDataType.BOOLEAN,
              requirement = FieldRequirement.OPTIONAL,
              enumOptions = listOf("True", "False"),
          ),
          field(
              key = "step_up_coupon_pa_pct_bex_logic",
              category = CATEGORY_COUPON_STRUCTURE,
              displayName = "Step-up Coupon (p.a.) (%) - BEX Logic",
              dataType = FieldDataType.STRING,
              requirement = FieldRequirement.MANDATORY,
              enumOptions = listOf("N/A", "Auto-Generate", "Manual Entry", "System Override"),
          ),
          field(
              key = "step_up_coupon_pa_pct",
              category = CATEGORY_COUPON_STRUCTURE,
              displayName = "Step-up Coupon (p.a.) (%)",
              dataType = FieldDataType.DOUBLE,
              requirement = FieldRequirement.OPTIONAL,
          ),
          field(
              key = "lock_in_coupon_pa_pct_option",
              category = CATEGORY_COUPON_STRUCTURE,
              displayName = "Lock-in Coupon (p.a.) (%) - Option",
              dataType = FieldDataType.STRING,
              requirement = FieldRequirement.MANDATORY,
              enumOptions = listOf("Required", "Not Required", "Optional"),
          ),
          field(
              key = "lock_in_coupon_pa_pct_in_email_conf",
              category = CATEGORY_COUPON_STRUCTURE,
              displayName = "Lock-in Coupon (p.a.) (%) - In email conf",
              dataType = FieldDataType.BOOLEAN,
              requirement = FieldRequirement.OPTIONAL,
              enumOptions = listOf("True", "False"),
          ),
          field(
              key = "lock_in_coupon_pa_pct_bex_logic",
              category = CATEGORY_COUPON_STRUCTURE,
              displayName = "Lock-in Coupon (p.a.) (%) - BEX Logic",
              dataType = FieldDataType.STRING,
              requirement = FieldRequirement.MANDATORY,
              enumOptions = listOf("N/A", "Auto-Generate", "Manual Entry", "System Override"),
          ),
          field(
              key = "lock_in_coupon_pa_pct",
              category = CATEGORY_COUPON_STRUCTURE,
              displayName = "Lock-in Coupon (p.a.) (%)",
              dataType = FieldDataType.DOUBLE,
              requirement = FieldRequirement.OPTIONAL,
          ),
          field(
              key = "floating_rate_cpn_pa_ref_index_plus_pct_option",
              category = CATEGORY_COUPON_STRUCTURE,
              displayName = "Floating rate Cpn p.a. (Ref. Index + %) - Option",
              dataType = FieldDataType.STRING,
              requirement = FieldRequirement.MANDATORY,
              enumOptions = listOf("Required", "Not Required", "Optional"),
          ),
          field(
              key = "floating_rate_cpn_pa_ref_index_plus_pct_in_email_conf",
              category = CATEGORY_COUPON_STRUCTURE,
              displayName = "Floating rate Cpn p.a. (Ref. Index + %) - In email conf",
              dataType = FieldDataType.BOOLEAN,
              requirement = FieldRequirement.OPTIONAL,
              enumOptions = listOf("True", "False"),
          ),
          field(
              key = "floating_rate_cpn_pa_ref_index_plus_pct_bex_logic",
              category = CATEGORY_COUPON_STRUCTURE,
              displayName = "Floating rate Cpn p.a. (Ref. Index + %) - BEX Logic",
              dataType = FieldDataType.STRING,
              requirement = FieldRequirement.MANDATORY,
              enumOptions = listOf("N/A", "Auto-Generate", "Manual Entry", "System Override"),
          ),
          field(
              key = "floating_rate_cpn_pa_ref_index_plus_pct",
              category = CATEGORY_COUPON_STRUCTURE,
              displayName = "Floating rate Cpn p.a. (Ref. Index + %)",
              dataType = FieldDataType.DOUBLE,
              requirement = FieldRequirement.OPTIONAL,
          ),
          field(
              key = "fixed_rate_cpn_pa_pct_option",
              category = CATEGORY_COUPON_STRUCTURE,
              displayName = "Fixed rate Cpn (p.a.) (%) - Option",
              dataType = FieldDataType.STRING,
              requirement = FieldRequirement.MANDATORY,
              enumOptions = listOf("Required", "Not Required", "Optional"),
          ),
          field(
              key = "fixed_rate_cpn_pa_pct_in_email_conf",
              category = CATEGORY_COUPON_STRUCTURE,
              displayName = "Fixed rate Cpn (p.a.) (%) - In email conf",
              dataType = FieldDataType.BOOLEAN,
              requirement = FieldRequirement.OPTIONAL,
              enumOptions = listOf("True", "False"),
          ),
          field(
              key = "fixed_rate_cpn_pa_pct_bex_logic",
              category = CATEGORY_COUPON_STRUCTURE,
              displayName = "Fixed rate Cpn (p.a.) (%) - BEX Logic",
              dataType = FieldDataType.STRING,
              requirement = FieldRequirement.MANDATORY,
              enumOptions = listOf("N/A", "Auto-Generate", "Manual Entry", "System Override"),
          ),
          field(
              key = "fixed_rate_cpn_pa_pct",
              category = CATEGORY_COUPON_STRUCTURE,
              displayName = "Fixed rate Cpn (p.a.) (%)",
              dataType = FieldDataType.DOUBLE,
              requirement = FieldRequirement.OPTIONAL,
          ),
          field(
              key = "cms_rate_pct_option",
              category = CATEGORY_COUPON_STRUCTURE,
              displayName = "CMS rate (%) - Option",
              dataType = FieldDataType.STRING,
              requirement = FieldRequirement.MANDATORY,
              enumOptions = listOf("Required", "Not Required", "Optional"),
          ),
          field(
              key = "cms_rate_pct_in_email_conf",
              category = CATEGORY_COUPON_STRUCTURE,
              displayName = "CMS rate (%) - In email conf",
              dataType = FieldDataType.BOOLEAN,
              requirement = FieldRequirement.OPTIONAL,
              enumOptions = listOf("True", "False"),
          ),
          field(
              key = "cms_rate_pct_bex_logic",
              category = CATEGORY_COUPON_STRUCTURE,
              displayName = "CMS rate (%) - BEX Logic",
              dataType = FieldDataType.STRING,
              requirement = FieldRequirement.MANDATORY,
              enumOptions = listOf("N/A", "Auto-Generate", "Manual Entry", "System Override"),
          ),
          field(
              key = "cms_rate_pct",
              category = CATEGORY_COUPON_STRUCTURE,
              displayName = "CMS rate (%)",
              dataType = FieldDataType.DOUBLE,
              requirement = FieldRequirement.OPTIONAL,
          ),
          field(
              key = "put_strike_pct_option",
              category = CATEGORY_BARRIERS_AND_LEVELS,
              displayName = "Put Strike (%) - Option",
              dataType = FieldDataType.STRING,
              requirement = FieldRequirement.MANDATORY,
              enumOptions = listOf("Required", "Not Required", "Optional"),
          ),
          field(
              key = "put_strike_pct_in_email_conf",
              category = CATEGORY_BARRIERS_AND_LEVELS,
              displayName = "Put Strike (%) - In email conf",
              dataType = FieldDataType.BOOLEAN,
              requirement = FieldRequirement.OPTIONAL,
              enumOptions = listOf("True", "False"),
          ),
          field(
              key = "put_strike_pct_bex_logic",
              category = CATEGORY_BARRIERS_AND_LEVELS,
              displayName = "Put Strike (%) - BEX Logic",
              dataType = FieldDataType.STRING,
              requirement = FieldRequirement.MANDATORY,
              enumOptions = listOf("N/A", "Auto-Generate", "Manual Entry", "System Override"),
          ),
          field(
              key = "put_strike_pct",
              category = CATEGORY_BARRIERS_AND_LEVELS,
              displayName = "Put Strike (%)",
              dataType = FieldDataType.DOUBLE,
              requirement = FieldRequirement.OPTIONAL,
          ),
          field(
              key = "callable_level_pct_option",
              category = CATEGORY_BARRIERS_AND_LEVELS,
              displayName = "Callable Level (%) - Option",
              dataType = FieldDataType.STRING,
              requirement = FieldRequirement.MANDATORY,
              enumOptions = listOf("Required", "Not Required", "Optional"),
          ),
          field(
              key = "callable_level_pct_in_email_conf",
              category = CATEGORY_BARRIERS_AND_LEVELS,
              displayName = "Callable Level (%) - In email conf",
              dataType = FieldDataType.BOOLEAN,
              requirement = FieldRequirement.OPTIONAL,
              enumOptions = listOf("True", "False"),
          ),
          field(
              key = "callable_level_pct_bex_logic",
              category = CATEGORY_BARRIERS_AND_LEVELS,
              displayName = "Callable Level (%) - BEX Logic",
              dataType = FieldDataType.STRING,
              requirement = FieldRequirement.MANDATORY,
              enumOptions = listOf("N/A", "Auto-Generate", "Manual Entry", "System Override"),
          ),
          field(
              key = "callable_level_pct",
              category = CATEGORY_BARRIERS_AND_LEVELS,
              displayName = "Callable Level (%)",
              dataType = FieldDataType.DOUBLE,
              requirement = FieldRequirement.OPTIONAL,
          ),
          field(
              key = "callable_after_option",
              category = CATEGORY_BARRIERS_AND_LEVELS,
              displayName = "Callable after - Option",
              dataType = FieldDataType.STRING,
              requirement = FieldRequirement.MANDATORY,
              enumOptions = listOf("Required", "Not Required", "Optional"),
          ),
          field(
              key = "callable_after_in_email_conf",
              category = CATEGORY_BARRIERS_AND_LEVELS,
              displayName = "Callable after - In email conf",
              dataType = FieldDataType.BOOLEAN,
              requirement = FieldRequirement.OPTIONAL,
              enumOptions = listOf("True", "False"),
          ),
          field(
              key = "callable_after_bex_logic",
              category = CATEGORY_BARRIERS_AND_LEVELS,
              displayName = "Callable after - BEX Logic",
              dataType = FieldDataType.STRING,
              requirement = FieldRequirement.MANDATORY,
              enumOptions = listOf("N/A", "Auto-Generate", "Manual Entry", "System Override"),
          ),
          field(
              key = "callable_after",
              category = CATEGORY_BARRIERS_AND_LEVELS,
              displayName = "Callable after",
              dataType = FieldDataType.STRING,
              requirement = FieldRequirement.OPTIONAL,
          ),
          field(
              key = "putable_after_option",
              category = CATEGORY_BARRIERS_AND_LEVELS,
              displayName = "Putable after - Option",
              dataType = FieldDataType.STRING,
              requirement = FieldRequirement.MANDATORY,
              enumOptions = listOf("Required", "Not Required", "Optional"),
          ),
          field(
              key = "putable_after_in_email_conf",
              category = CATEGORY_BARRIERS_AND_LEVELS,
              displayName = "Putable after - In email conf",
              dataType = FieldDataType.BOOLEAN,
              requirement = FieldRequirement.OPTIONAL,
              enumOptions = listOf("True", "False"),
          ),
          field(
              key = "putable_after_bex_logic",
              category = CATEGORY_BARRIERS_AND_LEVELS,
              displayName = "Putable after - BEX Logic",
              dataType = FieldDataType.STRING,
              requirement = FieldRequirement.MANDATORY,
              enumOptions = listOf("N/A", "Auto-Generate", "Manual Entry", "System Override"),
          ),
          field(
              key = "putable_after",
              category = CATEGORY_BARRIERS_AND_LEVELS,
              displayName = "Putable after",
              dataType = FieldDataType.STRING,
              requirement = FieldRequirement.OPTIONAL,
          ),
          field(
              key = "stepdown_by_pct_option",
              category = CATEGORY_BARRIERS_AND_LEVELS,
              displayName = "Stepdown by (%) - Option",
              dataType = FieldDataType.STRING,
              requirement = FieldRequirement.MANDATORY,
              enumOptions = listOf("Required", "Not Required", "Optional"),
          ),
          field(
              key = "stepdown_by_pct_in_email_conf",
              category = CATEGORY_BARRIERS_AND_LEVELS,
              displayName = "Stepdown by (%) - In email conf",
              dataType = FieldDataType.BOOLEAN,
              requirement = FieldRequirement.OPTIONAL,
              enumOptions = listOf("True", "False"),
          ),
          field(
              key = "stepdown_by_pct_bex_logic",
              category = CATEGORY_BARRIERS_AND_LEVELS,
              displayName = "Stepdown by (%) - BEX Logic",
              dataType = FieldDataType.STRING,
              requirement = FieldRequirement.MANDATORY,
              enumOptions = listOf("N/A", "Auto-Generate", "Manual Entry", "System Override"),
          ),
          field(
              key = "stepdown_by_pct",
              category = CATEGORY_BARRIERS_AND_LEVELS,
              displayName = "Stepdown by (%)",
              dataType = FieldDataType.DOUBLE,
              requirement = FieldRequirement.OPTIONAL,
          ),
          field(
              key = "knock_out_barrier_continuous_monitoring_pct_option",
              category = CATEGORY_BARRIERS_AND_LEVELS,
              displayName = "Knock-Out Barrier (Continuous monitoring %) - Option",
              dataType = FieldDataType.STRING,
              requirement = FieldRequirement.MANDATORY,
              enumOptions = listOf("Required", "Not Required", "Optional"),
          ),
          field(
              key = "knock_out_barrier_continuous_monitoring_pct_in_email_conf",
              category = CATEGORY_BARRIERS_AND_LEVELS,
              displayName = "Knock-Out Barrier (Continuous monitoring %) - In email conf",
              dataType = FieldDataType.BOOLEAN,
              requirement = FieldRequirement.OPTIONAL,
              enumOptions = listOf("True", "False"),
          ),
          field(
              key = "knock_out_barrier_continuous_monitoring_pct_bex_logic",
              category = CATEGORY_BARRIERS_AND_LEVELS,
              displayName = "Knock-Out Barrier (Continuous monitoring %) - BEX Logic",
              dataType = FieldDataType.STRING,
              requirement = FieldRequirement.MANDATORY,
              enumOptions = listOf("N/A", "Auto-Generate", "Manual Entry", "System Override"),
          ),
          field(
              key = "knock_out_barrier_continuous_monitoring_pct",
              category = CATEGORY_BARRIERS_AND_LEVELS,
              displayName = "Knock-Out Barrier (Continuous monitoring %)",
              dataType = FieldDataType.DOUBLE,
              requirement = FieldRequirement.OPTIONAL,
          ),
          field(
              key = "knock_out_barrier_daily_close_monitoring_pct_option",
              category = CATEGORY_BARRIERS_AND_LEVELS,
              displayName = "Knock-Out Barrier (Daily close monitoring %) - Option",
              dataType = FieldDataType.STRING,
              requirement = FieldRequirement.MANDATORY,
              enumOptions = listOf("Required", "Not Required", "Optional"),
          ),
          field(
              key = "knock_out_barrier_daily_close_monitoring_pct_in_email_conf",
              category = CATEGORY_BARRIERS_AND_LEVELS,
              displayName = "Knock-Out Barrier (Daily close monitoring %) - In email conf",
              dataType = FieldDataType.BOOLEAN,
              requirement = FieldRequirement.OPTIONAL,
              enumOptions = listOf("True", "False"),
          ),
          field(
              key = "knock_out_barrier_daily_close_monitoring_pct_bex_logic",
              category = CATEGORY_BARRIERS_AND_LEVELS,
              displayName = "Knock-Out Barrier (Daily close monitoring %) - BEX Logic",
              dataType = FieldDataType.STRING,
              requirement = FieldRequirement.MANDATORY,
              enumOptions = listOf("N/A", "Auto-Generate", "Manual Entry", "System Override"),
          ),
          field(
              key = "knock_out_barrier_daily_close_monitoring_pct",
              category = CATEGORY_BARRIERS_AND_LEVELS,
              displayName = "Knock-Out Barrier (Daily close monitoring %)",
              dataType = FieldDataType.DOUBLE,
              requirement = FieldRequirement.OPTIONAL,
          ),
          field(
              key = "knock_out_barrier_maturity_monitoring_pct_option",
              category = CATEGORY_BARRIERS_AND_LEVELS,
              displayName = "Knock-Out Barrier (Maturity monitoring %) - Option",
              dataType = FieldDataType.STRING,
              requirement = FieldRequirement.MANDATORY,
              enumOptions = listOf("Required", "Not Required", "Optional"),
          ),
          field(
              key = "knock_out_barrier_maturity_monitoring_pct_in_email_conf",
              category = CATEGORY_BARRIERS_AND_LEVELS,
              displayName = "Knock-Out Barrier (Maturity monitoring %) - In email conf",
              dataType = FieldDataType.BOOLEAN,
              requirement = FieldRequirement.OPTIONAL,
              enumOptions = listOf("True", "False"),
          ),
          field(
              key = "knock_out_barrier_maturity_monitoring_pct_bex_logic",
              category = CATEGORY_BARRIERS_AND_LEVELS,
              displayName = "Knock-Out Barrier (Maturity monitoring %) - BEX Logic",
              dataType = FieldDataType.STRING,
              requirement = FieldRequirement.MANDATORY,
              enumOptions = listOf("N/A", "Auto-Generate", "Manual Entry", "System Override"),
          ),
          field(
              key = "knock_out_barrier_maturity_monitoring_pct",
              category = CATEGORY_BARRIERS_AND_LEVELS,
              displayName = "Knock-Out Barrier (Maturity monitoring %)",
              dataType = FieldDataType.DOUBLE,
              requirement = FieldRequirement.OPTIONAL,
          ),
          field(
              key = "capital_return_level_pct_option",
              category = CATEGORY_BARRIERS_AND_LEVELS,
              displayName = "Capital Return Level (%) - Option",
              dataType = FieldDataType.STRING,
              requirement = FieldRequirement.MANDATORY,
              enumOptions = listOf("Required", "Not Required", "Optional"),
          ),
          field(
              key = "capital_return_level_pct_in_email_conf",
              category = CATEGORY_BARRIERS_AND_LEVELS,
              displayName = "Capital Return Level (%) - In email conf",
              dataType = FieldDataType.BOOLEAN,
              requirement = FieldRequirement.OPTIONAL,
              enumOptions = listOf("True", "False"),
          ),
          field(
              key = "capital_return_level_pct_bex_logic",
              category = CATEGORY_BARRIERS_AND_LEVELS,
              displayName = "Capital Return Level (%) - BEX Logic",
              dataType = FieldDataType.STRING,
              requirement = FieldRequirement.MANDATORY,
              enumOptions = listOf("N/A", "Auto-Generate", "Manual Entry", "System Override"),
          ),
          field(
              key = "capital_return_level_pct",
              category = CATEGORY_BARRIERS_AND_LEVELS,
              displayName = "Capital Return Level (%)",
              dataType = FieldDataType.DOUBLE,
              requirement = FieldRequirement.OPTIONAL,
          ),
          field(
              key = "coupon_barrier_option",
              category = CATEGORY_BARRIERS_AND_LEVELS,
              displayName = "Coupon Barrier - Option",
              dataType = FieldDataType.STRING,
              requirement = FieldRequirement.MANDATORY,
              enumOptions = listOf("Required", "Not Required", "Optional"),
          ),
          field(
              key = "coupon_barrier_in_email_conf",
              category = CATEGORY_BARRIERS_AND_LEVELS,
              displayName = "Coupon Barrier - In email conf",
              dataType = FieldDataType.BOOLEAN,
              requirement = FieldRequirement.OPTIONAL,
              enumOptions = listOf("True", "False"),
          ),
          field(
              key = "coupon_barrier_bex_logic",
              category = CATEGORY_BARRIERS_AND_LEVELS,
              displayName = "Coupon Barrier - BEX Logic",
              dataType = FieldDataType.STRING,
              requirement = FieldRequirement.MANDATORY,
              enumOptions = listOf("N/A", "Auto-Generate", "Manual Entry", "System Override"),
          ),
          field(
              key = "coupon_barrier",
              category = CATEGORY_BARRIERS_AND_LEVELS,
              displayName = "Coupon Barrier",
              dataType = FieldDataType.STRING,
              requirement = FieldRequirement.OPTIONAL,
          ),
          field(
              key = "lower_barrier_pct_option",
              category = CATEGORY_BARRIERS_AND_LEVELS,
              displayName = "Lower Barrier (%) - Option",
              dataType = FieldDataType.STRING,
              requirement = FieldRequirement.MANDATORY,
              enumOptions = listOf("Required", "Not Required", "Optional"),
          ),
          field(
              key = "lower_barrier_pct_in_email_conf",
              category = CATEGORY_BARRIERS_AND_LEVELS,
              displayName = "Lower Barrier (%) - In email conf",
              dataType = FieldDataType.BOOLEAN,
              requirement = FieldRequirement.OPTIONAL,
              enumOptions = listOf("True", "False"),
          ),
          field(
              key = "lower_barrier_pct_bex_logic",
              category = CATEGORY_BARRIERS_AND_LEVELS,
              displayName = "Lower Barrier (%) - BEX Logic",
              dataType = FieldDataType.STRING,
              requirement = FieldRequirement.MANDATORY,
              enumOptions = listOf("N/A", "Auto-Generate", "Manual Entry", "System Override"),
          ),
          field(
              key = "lower_barrier_pct",
              category = CATEGORY_BARRIERS_AND_LEVELS,
              displayName = "Lower Barrier (%)",
              dataType = FieldDataType.DOUBLE,
              requirement = FieldRequirement.OPTIONAL,
          ),
          field(
              key = "upper_barrier_pct_option",
              category = CATEGORY_BARRIERS_AND_LEVELS,
              displayName = "Upper Barrier (%) - Option",
              dataType = FieldDataType.STRING,
              requirement = FieldRequirement.MANDATORY,
              enumOptions = listOf("Required", "Not Required", "Optional"),
          ),
          field(
              key = "upper_barrier_pct_in_email_conf",
              category = CATEGORY_BARRIERS_AND_LEVELS,
              displayName = "Upper Barrier (%) - In email conf",
              dataType = FieldDataType.BOOLEAN,
              requirement = FieldRequirement.OPTIONAL,
              enumOptions = listOf("True", "False"),
          ),
          field(
              key = "upper_barrier_pct_bex_logic",
              category = CATEGORY_BARRIERS_AND_LEVELS,
              displayName = "Upper Barrier (%) - BEX Logic",
              dataType = FieldDataType.STRING,
              requirement = FieldRequirement.MANDATORY,
              enumOptions = listOf("N/A", "Auto-Generate", "Manual Entry", "System Override"),
          ),
          field(
              key = "upper_barrier_pct",
              category = CATEGORY_BARRIERS_AND_LEVELS,
              displayName = "Upper Barrier (%)",
              dataType = FieldDataType.DOUBLE,
              requirement = FieldRequirement.OPTIONAL,
          ),
          field(
              key = "outer_barrier_pct_option",
              category = CATEGORY_BARRIERS_AND_LEVELS,
              displayName = "Outer Barrier (%) - Option",
              dataType = FieldDataType.STRING,
              requirement = FieldRequirement.MANDATORY,
              enumOptions = listOf("Required", "Not Required", "Optional"),
          ),
          field(
              key = "outer_barrier_pct_in_email_conf",
              category = CATEGORY_BARRIERS_AND_LEVELS,
              displayName = "Outer Barrier (%) - In email conf",
              dataType = FieldDataType.BOOLEAN,
              requirement = FieldRequirement.OPTIONAL,
              enumOptions = listOf("True", "False"),
          ),
          field(
              key = "outer_barrier_pct_bex_logic",
              category = CATEGORY_BARRIERS_AND_LEVELS,
              displayName = "Outer Barrier (%) - BEX Logic",
              dataType = FieldDataType.STRING,
              requirement = FieldRequirement.MANDATORY,
              enumOptions = listOf("N/A", "Auto-Generate", "Manual Entry", "System Override"),
          ),
          field(
              key = "outer_barrier_pct",
              category = CATEGORY_BARRIERS_AND_LEVELS,
              displayName = "Outer Barrier (%)",
              dataType = FieldDataType.DOUBLE,
              requirement = FieldRequirement.OPTIONAL,
          ),
          field(
              key = "kick_in_barrier_continuous_monitoring_pct_option",
              category = CATEGORY_BARRIERS_AND_LEVELS,
              displayName = "Kick-In Barrier (Continuous monitoring %) - Option",
              dataType = FieldDataType.STRING,
              requirement = FieldRequirement.MANDATORY,
              enumOptions = listOf("Required", "Not Required", "Optional"),
          ),
          field(
              key = "kick_in_barrier_continuous_monitoring_pct_in_email_conf",
              category = CATEGORY_BARRIERS_AND_LEVELS,
              displayName = "Kick-In Barrier (Continuous monitoring %) - In email conf",
              dataType = FieldDataType.BOOLEAN,
              requirement = FieldRequirement.OPTIONAL,
              enumOptions = listOf("True", "False"),
          ),
          field(
              key = "kick_in_barrier_continuous_monitoring_pct_bex_logic",
              category = CATEGORY_BARRIERS_AND_LEVELS,
              displayName = "Kick-In Barrier (Continuous monitoring %) - BEX Logic",
              dataType = FieldDataType.STRING,
              requirement = FieldRequirement.MANDATORY,
              enumOptions = listOf("N/A", "Auto-Generate", "Manual Entry", "System Override"),
          ),
          field(
              key = "kick_in_barrier_continuous_monitoring_pct",
              category = CATEGORY_BARRIERS_AND_LEVELS,
              displayName = "Kick-In Barrier (Continuous monitoring %)",
              dataType = FieldDataType.DOUBLE,
              requirement = FieldRequirement.OPTIONAL,
          ),
          field(
              key = "kick_in_barrier_daily_close_monitoring_pct_option",
              category = CATEGORY_BARRIERS_AND_LEVELS,
              displayName = "Kick-In Barrier (Daily close monitoring %) - Option",
              dataType = FieldDataType.STRING,
              requirement = FieldRequirement.MANDATORY,
              enumOptions = listOf("Required", "Not Required", "Optional"),
          ),
          field(
              key = "kick_in_barrier_daily_close_monitoring_pct_in_email_conf",
              category = CATEGORY_BARRIERS_AND_LEVELS,
              displayName = "Kick-In Barrier (Daily close monitoring %) - In email conf",
              dataType = FieldDataType.BOOLEAN,
              requirement = FieldRequirement.OPTIONAL,
              enumOptions = listOf("True", "False"),
          ),
          field(
              key = "kick_in_barrier_daily_close_monitoring_pct_bex_logic",
              category = CATEGORY_BARRIERS_AND_LEVELS,
              displayName = "Kick-In Barrier (Daily close monitoring %) - BEX Logic",
              dataType = FieldDataType.STRING,
              requirement = FieldRequirement.MANDATORY,
              enumOptions = listOf("N/A", "Auto-Generate", "Manual Entry", "System Override"),
          ),
          field(
              key = "kick_in_barrier_daily_close_monitoring_pct",
              category = CATEGORY_BARRIERS_AND_LEVELS,
              displayName = "Kick-In Barrier (Daily close monitoring %)",
              dataType = FieldDataType.DOUBLE,
              requirement = FieldRequirement.OPTIONAL,
          ),
          field(
              key = "kick_in_barrier_maturity_monitoring_pct_option",
              category = CATEGORY_BARRIERS_AND_LEVELS,
              displayName = "Kick-In Barrier (Maturity monitoring %) - Option",
              dataType = FieldDataType.STRING,
              requirement = FieldRequirement.MANDATORY,
              enumOptions = listOf("Required", "Not Required", "Optional"),
          ),
          field(
              key = "kick_in_barrier_maturity_monitoring_pct_in_email_conf",
              category = CATEGORY_BARRIERS_AND_LEVELS,
              displayName = "Kick-In Barrier (Maturity monitoring %) - In email conf",
              dataType = FieldDataType.BOOLEAN,
              requirement = FieldRequirement.OPTIONAL,
              enumOptions = listOf("True", "False"),
          ),
          field(
              key = "kick_in_barrier_maturity_monitoring_pct_bex_logic",
              category = CATEGORY_BARRIERS_AND_LEVELS,
              displayName = "Kick-In Barrier (Maturity monitoring %) - BEX Logic",
              dataType = FieldDataType.STRING,
              requirement = FieldRequirement.MANDATORY,
              enumOptions = listOf("N/A", "Auto-Generate", "Manual Entry", "System Override"),
          ),
          field(
              key = "kick_in_barrier_maturity_monitoring_pct",
              category = CATEGORY_BARRIERS_AND_LEVELS,
              displayName = "Kick-In Barrier (Maturity monitoring %)",
              dataType = FieldDataType.DOUBLE,
              requirement = FieldRequirement.OPTIONAL,
          ),
          field(
              key = "lock_in_barrier_pct_option",
              category = CATEGORY_BARRIERS_AND_LEVELS,
              displayName = "Lock-in Barrier (%) - Option",
              dataType = FieldDataType.STRING,
              requirement = FieldRequirement.MANDATORY,
              enumOptions = listOf("Required", "Not Required", "Optional"),
          ),
          field(
              key = "lock_in_barrier_pct_in_email_conf",
              category = CATEGORY_BARRIERS_AND_LEVELS,
              displayName = "Lock-in Barrier (%) - In email conf",
              dataType = FieldDataType.BOOLEAN,
              requirement = FieldRequirement.OPTIONAL,
              enumOptions = listOf("True", "False"),
          ),
          field(
              key = "lock_in_barrier_pct_bex_logic",
              category = CATEGORY_BARRIERS_AND_LEVELS,
              displayName = "Lock-in Barrier (%) - BEX Logic",
              dataType = FieldDataType.STRING,
              requirement = FieldRequirement.MANDATORY,
              enumOptions = listOf("N/A", "Auto-Generate", "Manual Entry", "System Override"),
          ),
          field(
              key = "lock_in_barrier_pct",
              category = CATEGORY_BARRIERS_AND_LEVELS,
              displayName = "Lock-in Barrier (%)",
              dataType = FieldDataType.DOUBLE,
              requirement = FieldRequirement.OPTIONAL,
          ),
          field(
              key = "callable_barrier_pct_option",
              category = CATEGORY_BARRIERS_AND_LEVELS,
              displayName = "Callable Barrier (%) - Option",
              dataType = FieldDataType.STRING,
              requirement = FieldRequirement.MANDATORY,
              enumOptions = listOf("Required", "Not Required", "Optional"),
          ),
          field(
              key = "callable_barrier_pct_in_email_conf",
              category = CATEGORY_BARRIERS_AND_LEVELS,
              displayName = "Callable Barrier (%) - In email conf",
              dataType = FieldDataType.BOOLEAN,
              requirement = FieldRequirement.OPTIONAL,
              enumOptions = listOf("True", "False"),
          ),
          field(
              key = "callable_barrier_pct_bex_logic",
              category = CATEGORY_BARRIERS_AND_LEVELS,
              displayName = "Callable Barrier (%) - BEX Logic",
              dataType = FieldDataType.STRING,
              requirement = FieldRequirement.MANDATORY,
              enumOptions = listOf("N/A", "Auto-Generate", "Manual Entry", "System Override"),
          ),
          field(
              key = "callable_barrier_pct",
              category = CATEGORY_BARRIERS_AND_LEVELS,
              displayName = "Callable Barrier (%)",
              dataType = FieldDataType.DOUBLE,
              requirement = FieldRequirement.OPTIONAL,
          ),
          field(
              key = "outperformance_barrier_pct_option",
              category = CATEGORY_BARRIERS_AND_LEVELS,
              displayName = "Outperformance barrier (%) - Option",
              dataType = FieldDataType.STRING,
              requirement = FieldRequirement.MANDATORY,
              enumOptions = listOf("Required", "Not Required", "Optional"),
          ),
          field(
              key = "outperformance_barrier_pct_in_email_conf",
              category = CATEGORY_BARRIERS_AND_LEVELS,
              displayName = "Outperformance barrier (%) - In email conf",
              dataType = FieldDataType.BOOLEAN,
              requirement = FieldRequirement.OPTIONAL,
              enumOptions = listOf("True", "False"),
          ),
          field(
              key = "outperformance_barrier_pct_bex_logic",
              category = CATEGORY_BARRIERS_AND_LEVELS,
              displayName = "Outperformance barrier (%) - BEX Logic",
              dataType = FieldDataType.STRING,
              requirement = FieldRequirement.MANDATORY,
              enumOptions = listOf("N/A", "Auto-Generate", "Manual Entry", "System Override"),
          ),
          field(
              key = "outperformance_barrier_pct",
              category = CATEGORY_BARRIERS_AND_LEVELS,
              displayName = "Outperformance barrier (%)",
              dataType = FieldDataType.DOUBLE,
              requirement = FieldRequirement.OPTIONAL,
          ),
          field(
              key = "underperformance_barrier_pct_option",
              category = CATEGORY_BARRIERS_AND_LEVELS,
              displayName = "Underperformance barrier (%) - Option",
              dataType = FieldDataType.STRING,
              requirement = FieldRequirement.MANDATORY,
              enumOptions = listOf("Required", "Not Required", "Optional"),
          ),
          field(
              key = "underperformance_barrier_pct_in_email_conf",
              category = CATEGORY_BARRIERS_AND_LEVELS,
              displayName = "Underperformance barrier (%) - In email conf",
              dataType = FieldDataType.BOOLEAN,
              requirement = FieldRequirement.OPTIONAL,
              enumOptions = listOf("True", "False"),
          ),
          field(
              key = "underperformance_barrier_pct_bex_logic",
              category = CATEGORY_BARRIERS_AND_LEVELS,
              displayName = "Underperformance barrier (%) - BEX Logic",
              dataType = FieldDataType.STRING,
              requirement = FieldRequirement.MANDATORY,
              enumOptions = listOf("N/A", "Auto-Generate", "Manual Entry", "System Override"),
          ),
          field(
              key = "underperformance_barrier_pct",
              category = CATEGORY_BARRIERS_AND_LEVELS,
              displayName = "Underperformance barrier (%)",
              dataType = FieldDataType.DOUBLE,
              requirement = FieldRequirement.OPTIONAL,
          ),
          field(
              key = "inner_barrier_pct_option",
              category = CATEGORY_BARRIERS_AND_LEVELS,
              displayName = "Inner Barrier (%) - Option",
              dataType = FieldDataType.STRING,
              requirement = FieldRequirement.MANDATORY,
              enumOptions = listOf("Required", "Not Required", "Optional"),
          ),
          field(
              key = "inner_barrier_pct_in_email_conf",
              category = CATEGORY_BARRIERS_AND_LEVELS,
              displayName = "Inner Barrier (%) - In email conf",
              dataType = FieldDataType.BOOLEAN,
              requirement = FieldRequirement.OPTIONAL,
              enumOptions = listOf("True", "False"),
          ),
          field(
              key = "inner_barrier_pct_bex_logic",
              category = CATEGORY_BARRIERS_AND_LEVELS,
              displayName = "Inner Barrier (%) - BEX Logic",
              dataType = FieldDataType.STRING,
              requirement = FieldRequirement.MANDATORY,
              enumOptions = listOf("N/A", "Auto-Generate", "Manual Entry", "System Override"),
          ),
          field(
              key = "inner_barrier_pct",
              category = CATEGORY_BARRIERS_AND_LEVELS,
              displayName = "Inner Barrier (%)",
              dataType = FieldDataType.DOUBLE,
              requirement = FieldRequirement.OPTIONAL,
          ),
          field(
              key = "floor_pct_option",
              category = CATEGORY_BARRIERS_AND_LEVELS,
              displayName = "Floor (%) - Option",
              dataType = FieldDataType.STRING,
              requirement = FieldRequirement.MANDATORY,
              enumOptions = listOf("Required", "Not Required", "Optional"),
          ),
          field(
              key = "floor_pct_in_email_conf",
              category = CATEGORY_BARRIERS_AND_LEVELS,
              displayName = "Floor (%) - In email conf",
              dataType = FieldDataType.BOOLEAN,
              requirement = FieldRequirement.OPTIONAL,
              enumOptions = listOf("True", "False"),
          ),
          field(
              key = "floor_pct_bex_logic",
              category = CATEGORY_BARRIERS_AND_LEVELS,
              displayName = "Floor (%) - BEX Logic",
              dataType = FieldDataType.STRING,
              requirement = FieldRequirement.MANDATORY,
              enumOptions = listOf("N/A", "Auto-Generate", "Manual Entry", "System Override"),
          ),
          field(
              key = "floor_pct",
              category = CATEGORY_BARRIERS_AND_LEVELS,
              displayName = "Floor (%)",
              dataType = FieldDataType.DOUBLE,
              requirement = FieldRequirement.OPTIONAL,
          ),
          field(
              key = "call_strike_pct_option",
              category = CATEGORY_BARRIERS_AND_LEVELS,
              displayName = "Call Strike (%) - Option",
              dataType = FieldDataType.STRING,
              requirement = FieldRequirement.MANDATORY,
              enumOptions = listOf("Required", "Not Required", "Optional"),
          ),
          field(
              key = "call_strike_pct_in_email_conf",
              category = CATEGORY_BARRIERS_AND_LEVELS,
              displayName = "Call Strike (%) - In email conf",
              dataType = FieldDataType.BOOLEAN,
              requirement = FieldRequirement.OPTIONAL,
              enumOptions = listOf("True", "False"),
          ),
          field(
              key = "call_strike_pct_bex_logic",
              category = CATEGORY_BARRIERS_AND_LEVELS,
              displayName = "Call Strike (%) - BEX Logic",
              dataType = FieldDataType.STRING,
              requirement = FieldRequirement.MANDATORY,
              enumOptions = listOf("N/A", "Auto-Generate", "Manual Entry", "System Override"),
          ),
          field(
              key = "call_strike_pct",
              category = CATEGORY_BARRIERS_AND_LEVELS,
              displayName = "Call Strike (%)",
              dataType = FieldDataType.DOUBLE,
              requirement = FieldRequirement.OPTIONAL,
          ),
          field(
              key = "upper_strike_pct_option",
              category = CATEGORY_BARRIERS_AND_LEVELS,
              displayName = "Upper Strike (%) - Option",
              dataType = FieldDataType.STRING,
              requirement = FieldRequirement.MANDATORY,
              enumOptions = listOf("Required", "Not Required", "Optional"),
          ),
          field(
              key = "upper_strike_pct_in_email_conf",
              category = CATEGORY_BARRIERS_AND_LEVELS,
              displayName = "Upper Strike (%) - In email conf",
              dataType = FieldDataType.BOOLEAN,
              requirement = FieldRequirement.OPTIONAL,
              enumOptions = listOf("True", "False"),
          ),
          field(
              key = "upper_strike_pct_bex_logic",
              category = CATEGORY_BARRIERS_AND_LEVELS,
              displayName = "Upper Strike (%) - BEX Logic",
              dataType = FieldDataType.STRING,
              requirement = FieldRequirement.MANDATORY,
              enumOptions = listOf("N/A", "Auto-Generate", "Manual Entry", "System Override"),
          ),
          field(
              key = "upper_strike_pct",
              category = CATEGORY_BARRIERS_AND_LEVELS,
              displayName = "Upper Strike (%)",
              dataType = FieldDataType.DOUBLE,
              requirement = FieldRequirement.OPTIONAL,
          ),
          field(
              key = "lower_strike_pct_option",
              category = CATEGORY_BARRIERS_AND_LEVELS,
              displayName = "Lower Strike (%) - Option",
              dataType = FieldDataType.STRING,
              requirement = FieldRequirement.MANDATORY,
              enumOptions = listOf("Required", "Not Required", "Optional"),
          ),
          field(
              key = "lower_strike_pct_in_email_conf",
              category = CATEGORY_BARRIERS_AND_LEVELS,
              displayName = "Lower Strike (%) - In email conf",
              dataType = FieldDataType.BOOLEAN,
              requirement = FieldRequirement.OPTIONAL,
              enumOptions = listOf("True", "False"),
          ),
          field(
              key = "lower_strike_pct_bex_logic",
              category = CATEGORY_BARRIERS_AND_LEVELS,
              displayName = "Lower Strike (%) - BEX Logic",
              dataType = FieldDataType.STRING,
              requirement = FieldRequirement.MANDATORY,
              enumOptions = listOf("N/A", "Auto-Generate", "Manual Entry", "System Override"),
          ),
          field(
              key = "lower_strike_pct",
              category = CATEGORY_BARRIERS_AND_LEVELS,
              displayName = "Lower Strike (%)",
              dataType = FieldDataType.DOUBLE,
              requirement = FieldRequirement.OPTIONAL,
          ),
          field(
              key = "underlyings_option",
              category = CATEGORY_MARKET_AND_TECHNICAL,
              displayName = "Underlyings - Option",
              dataType = FieldDataType.STRING,
              requirement = FieldRequirement.MANDATORY,
              enumOptions = listOf("Required", "Not Required", "Optional"),
          ),
          field(
              key = "underlyings_in_email_conf",
              category = CATEGORY_MARKET_AND_TECHNICAL,
              displayName = "Underlyings - In email conf",
              dataType = FieldDataType.BOOLEAN,
              requirement = FieldRequirement.OPTIONAL,
              enumOptions = listOf("True", "False"),
          ),
          field(
              key = "underlyings_bex_logic",
              category = CATEGORY_MARKET_AND_TECHNICAL,
              displayName = "Underlyings - BEX Logic",
              dataType = FieldDataType.STRING,
              requirement = FieldRequirement.MANDATORY,
              enumOptions = listOf("N/A", "Auto-Generate", "Manual Entry", "System Override"),
          ),
          field(
              key = "underlyings",
              category = CATEGORY_MARKET_AND_TECHNICAL,
              displayName = "Underlyings",
              dataType = FieldDataType.STRING,
              requirement = FieldRequirement.OPTIONAL,
          ),
          field(
              key = "underlying_option",
              category = CATEGORY_MARKET_AND_TECHNICAL,
              displayName = "Underlying - Option",
              dataType = FieldDataType.STRING,
              requirement = FieldRequirement.MANDATORY,
              enumOptions = listOf("Required", "Not Required", "Optional"),
          ),
          field(
              key = "underlying_in_email_conf",
              category = CATEGORY_MARKET_AND_TECHNICAL,
              displayName = "Underlying - In email conf",
              dataType = FieldDataType.BOOLEAN,
              requirement = FieldRequirement.OPTIONAL,
              enumOptions = listOf("True", "False"),
          ),
          field(
              key = "underlying_bex_logic",
              category = CATEGORY_MARKET_AND_TECHNICAL,
              displayName = "Underlying - BEX Logic",
              dataType = FieldDataType.STRING,
              requirement = FieldRequirement.MANDATORY,
              enumOptions = listOf("N/A", "Auto-Generate", "Manual Entry", "System Override"),
          ),
          field(
              key = "underlying",
              category = CATEGORY_MARKET_AND_TECHNICAL,
              displayName = "Underlying",
              dataType = FieldDataType.STRING,
              requirement = FieldRequirement.OPTIONAL,
          ),
          field(
              key = "bullish_underlying_basket_option",
              category = CATEGORY_MARKET_AND_TECHNICAL,
              displayName = "Bullish Underlying basket - Option",
              dataType = FieldDataType.STRING,
              requirement = FieldRequirement.MANDATORY,
              enumOptions = listOf("Required", "Not Required", "Optional"),
          ),
          field(
              key = "bullish_underlying_basket_in_email_conf",
              category = CATEGORY_MARKET_AND_TECHNICAL,
              displayName = "Bullish Underlying basket - In email conf",
              dataType = FieldDataType.BOOLEAN,
              requirement = FieldRequirement.OPTIONAL,
              enumOptions = listOf("True", "False"),
          ),
          field(
              key = "bullish_underlying_basket_bex_logic",
              category = CATEGORY_MARKET_AND_TECHNICAL,
              displayName = "Bullish Underlying basket - BEX Logic",
              dataType = FieldDataType.STRING,
              requirement = FieldRequirement.MANDATORY,
              enumOptions = listOf("N/A", "Auto-Generate", "Manual Entry", "System Override"),
          ),
          field(
              key = "bullish_underlying_basket",
              category = CATEGORY_MARKET_AND_TECHNICAL,
              displayName = "Bullish Underlying basket",
              dataType = FieldDataType.STRING,
              requirement = FieldRequirement.OPTIONAL,
          ),
          field(
              key = "bearish_underlying_basket_option",
              category = CATEGORY_MARKET_AND_TECHNICAL,
              displayName = "Bearish Underlying basket - Option",
              dataType = FieldDataType.STRING,
              requirement = FieldRequirement.MANDATORY,
              enumOptions = listOf("Required", "Not Required", "Optional"),
          ),
          field(
              key = "bearish_underlying_basket_in_email_conf",
              category = CATEGORY_MARKET_AND_TECHNICAL,
              displayName = "Bearish Underlying basket - In email conf",
              dataType = FieldDataType.BOOLEAN,
              requirement = FieldRequirement.OPTIONAL,
              enumOptions = listOf("True", "False"),
          ),
          field(
              key = "bearish_underlying_basket_bex_logic",
              category = CATEGORY_MARKET_AND_TECHNICAL,
              displayName = "Bearish Underlying basket - BEX Logic",
              dataType = FieldDataType.STRING,
              requirement = FieldRequirement.MANDATORY,
              enumOptions = listOf("N/A", "Auto-Generate", "Manual Entry", "System Override"),
          ),
          field(
              key = "bearish_underlying_basket",
              category = CATEGORY_MARKET_AND_TECHNICAL,
              displayName = "Bearish Underlying basket",
              dataType = FieldDataType.STRING,
              requirement = FieldRequirement.OPTIONAL,
          ),
          field(
              key = "called_date_option",
              category = CATEGORY_MARKET_AND_TECHNICAL,
              displayName = "Called Date - Option",
              dataType = FieldDataType.STRING,
              requirement = FieldRequirement.MANDATORY,
              enumOptions = listOf("Required", "Not Required", "Optional"),
          ),
          field(
              key = "called_date_in_email_conf",
              category = CATEGORY_MARKET_AND_TECHNICAL,
              displayName = "Called Date - In email conf",
              dataType = FieldDataType.BOOLEAN,
              requirement = FieldRequirement.OPTIONAL,
              enumOptions = listOf("True", "False"),
          ),
          field(
              key = "called_date_bex_logic",
              category = CATEGORY_MARKET_AND_TECHNICAL,
              displayName = "Called Date - BEX Logic",
              dataType = FieldDataType.STRING,
              requirement = FieldRequirement.MANDATORY,
              enumOptions = listOf("N/A", "Auto-Generate", "Manual Entry", "System Override"),
          ),
          field(
              key = "called_date",
              category = CATEGORY_MARKET_AND_TECHNICAL,
              displayName = "Called Date",
              dataType = FieldDataType.STRING,
              requirement = FieldRequirement.OPTIONAL,
          ),
          field(
              key = "cap_pct_option",
              category = CATEGORY_MARKET_AND_TECHNICAL,
              displayName = "Cap (%) - Option",
              dataType = FieldDataType.STRING,
              requirement = FieldRequirement.MANDATORY,
              enumOptions = listOf("Required", "Not Required", "Optional"),
          ),
          field(
              key = "cap_pct_in_email_conf",
              category = CATEGORY_MARKET_AND_TECHNICAL,
              displayName = "Cap (%) - In email conf",
              dataType = FieldDataType.BOOLEAN,
              requirement = FieldRequirement.OPTIONAL,
              enumOptions = listOf("True", "False"),
          ),
          field(
              key = "cap_pct_bex_logic",
              category = CATEGORY_MARKET_AND_TECHNICAL,
              displayName = "Cap (%) - BEX Logic",
              dataType = FieldDataType.STRING,
              requirement = FieldRequirement.MANDATORY,
              enumOptions = listOf("N/A", "Auto-Generate", "Manual Entry", "System Override"),
          ),
          field(
              key = "cap_pct",
              category = CATEGORY_MARKET_AND_TECHNICAL,
              displayName = "Cap (%)",
              dataType = FieldDataType.DOUBLE,
              requirement = FieldRequirement.OPTIONAL,
          ),
          field(
              key = "upside_participation_pct_option",
              category = CATEGORY_MARKET_AND_TECHNICAL,
              displayName = "Upside Participation (%) - Option",
              dataType = FieldDataType.STRING,
              requirement = FieldRequirement.MANDATORY,
              enumOptions = listOf("Required", "Not Required", "Optional"),
          ),
          field(
              key = "upside_participation_pct_in_email_conf",
              category = CATEGORY_MARKET_AND_TECHNICAL,
              displayName = "Upside Participation (%) - In email conf",
              dataType = FieldDataType.BOOLEAN,
              requirement = FieldRequirement.OPTIONAL,
              enumOptions = listOf("True", "False"),
          ),
          field(
              key = "upside_participation_pct_bex_logic",
              category = CATEGORY_MARKET_AND_TECHNICAL,
              displayName = "Upside Participation (%) - BEX Logic",
              dataType = FieldDataType.STRING,
              requirement = FieldRequirement.MANDATORY,
              enumOptions = listOf("N/A", "Auto-Generate", "Manual Entry", "System Override"),
          ),
          field(
              key = "upside_participation_pct",
              category = CATEGORY_MARKET_AND_TECHNICAL,
              displayName = "Upside Participation (%)",
              dataType = FieldDataType.DOUBLE,
              requirement = FieldRequirement.OPTIONAL,
          ),
          field(
              key = "downside_participation_pct_option",
              category = CATEGORY_MARKET_AND_TECHNICAL,
              displayName = "Downside Participation (%) - Option",
              dataType = FieldDataType.STRING,
              requirement = FieldRequirement.MANDATORY,
              enumOptions = listOf("Required", "Not Required", "Optional"),
          ),
          field(
              key = "downside_participation_pct_in_email_conf",
              category = CATEGORY_MARKET_AND_TECHNICAL,
              displayName = "Downside Participation (%) - In email conf",
              dataType = FieldDataType.BOOLEAN,
              requirement = FieldRequirement.OPTIONAL,
              enumOptions = listOf("True", "False"),
          ),
          field(
              key = "downside_participation_pct_bex_logic",
              category = CATEGORY_MARKET_AND_TECHNICAL,
              displayName = "Downside Participation (%) - BEX Logic",
              dataType = FieldDataType.STRING,
              requirement = FieldRequirement.MANDATORY,
              enumOptions = listOf("N/A", "Auto-Generate", "Manual Entry", "System Override"),
          ),
          field(
              key = "downside_participation_pct",
              category = CATEGORY_MARKET_AND_TECHNICAL,
              displayName = "Downside Participation (%)",
              dataType = FieldDataType.DOUBLE,
              requirement = FieldRequirement.OPTIONAL,
          ),
          field(
              key = "observation_frequency_option",
              category = CATEGORY_MARKET_AND_TECHNICAL,
              displayName = "Observation Frequency - Option",
              dataType = FieldDataType.STRING,
              requirement = FieldRequirement.MANDATORY,
              enumOptions = listOf("Required", "Not Required", "Optional"),
          ),
          field(
              key = "observation_frequency_in_email_conf",
              category = CATEGORY_MARKET_AND_TECHNICAL,
              displayName = "Observation Frequency - In email conf",
              dataType = FieldDataType.BOOLEAN,
              requirement = FieldRequirement.OPTIONAL,
              enumOptions = listOf("True", "False"),
          ),
          field(
              key = "observation_frequency_bex_logic",
              category = CATEGORY_MARKET_AND_TECHNICAL,
              displayName = "Observation Frequency - BEX Logic",
              dataType = FieldDataType.STRING,
              requirement = FieldRequirement.MANDATORY,
              enumOptions = listOf("N/A", "Auto-Generate", "Manual Entry", "System Override"),
          ),
          field(
              key = "observation_frequency",
              category = CATEGORY_MARKET_AND_TECHNICAL,
              displayName = "Observation Frequency",
              dataType = FieldDataType.STRING,
              requirement = FieldRequirement.OPTIONAL,
              enumOptions = listOf("Monthly", "Quarterly", "Semi-Annually", "Annually"),
          ),
          field(
              key = "no_of_callable_periods_option",
              category = CATEGORY_MARKET_AND_TECHNICAL,
              displayName = "No. of Callable periods - Option",
              dataType = FieldDataType.STRING,
              requirement = FieldRequirement.MANDATORY,
              enumOptions = listOf("Required", "Not Required", "Optional"),
          ),
          field(
              key = "no_of_callable_periods_in_email_conf",
              category = CATEGORY_MARKET_AND_TECHNICAL,
              displayName = "No. of Callable periods - In email conf",
              dataType = FieldDataType.BOOLEAN,
              requirement = FieldRequirement.OPTIONAL,
              enumOptions = listOf("True", "False"),
          ),
          field(
              key = "no_of_callable_periods_bex_logic",
              category = CATEGORY_MARKET_AND_TECHNICAL,
              displayName = "No. of Callable periods - BEX Logic",
              dataType = FieldDataType.STRING,
              requirement = FieldRequirement.MANDATORY,
              enumOptions = listOf("N/A", "Auto-Generate", "Manual Entry", "System Override"),
          ),
          field(
              key = "no_of_callable_periods",
              category = CATEGORY_MARKET_AND_TECHNICAL,
              displayName = "No. of Callable periods",
              dataType = FieldDataType.STRING,
              requirement = FieldRequirement.OPTIONAL,
          ),
          field(
              key = "ref_index_option",
              category = CATEGORY_MARKET_AND_TECHNICAL,
              displayName = "Ref. Index - Option",
              dataType = FieldDataType.STRING,
              requirement = FieldRequirement.MANDATORY,
              enumOptions = listOf("Required", "Not Required", "Optional"),
          ),
          field(
              key = "ref_index_in_email_conf",
              category = CATEGORY_MARKET_AND_TECHNICAL,
              displayName = "Ref. Index - In email conf",
              dataType = FieldDataType.BOOLEAN,
              requirement = FieldRequirement.OPTIONAL,
              enumOptions = listOf("True", "False"),
          ),
          field(
              key = "ref_index_bex_logic",
              category = CATEGORY_MARKET_AND_TECHNICAL,
              displayName = "Ref. Index - BEX Logic",
              dataType = FieldDataType.STRING,
              requirement = FieldRequirement.MANDATORY,
              enumOptions = listOf("N/A", "Auto-Generate", "Manual Entry", "System Override"),
          ),
          field(
              key = "ref_index",
              category = CATEGORY_MARKET_AND_TECHNICAL,
              displayName = "Ref. Index",
              dataType = FieldDataType.STRING,
              requirement = FieldRequirement.OPTIONAL,
          ),
          field(
              key = "gearing_ratio_option",
              category = CATEGORY_MARKET_AND_TECHNICAL,
              displayName = "Gearing Ratio - Option",
              dataType = FieldDataType.STRING,
              requirement = FieldRequirement.MANDATORY,
              enumOptions = listOf("Required", "Not Required", "Optional"),
          ),
          field(
              key = "gearing_ratio_in_email_conf",
              category = CATEGORY_MARKET_AND_TECHNICAL,
              displayName = "Gearing Ratio - In email conf",
              dataType = FieldDataType.BOOLEAN,
              requirement = FieldRequirement.OPTIONAL,
              enumOptions = listOf("True", "False"),
          ),
          field(
              key = "gearing_ratio_bex_logic",
              category = CATEGORY_MARKET_AND_TECHNICAL,
              displayName = "Gearing Ratio - BEX Logic",
              dataType = FieldDataType.STRING,
              requirement = FieldRequirement.MANDATORY,
              enumOptions = listOf("N/A", "Auto-Generate", "Manual Entry", "System Override"),
          ),
          field(
              key = "gearing_ratio",
              category = CATEGORY_MARKET_AND_TECHNICAL,
              displayName = "Gearing Ratio",
              dataType = FieldDataType.STRING,
              requirement = FieldRequirement.OPTIONAL,
          ),
          field(
              key = "no_of_guarantee_periods_option",
              category = CATEGORY_MARKET_AND_TECHNICAL,
              displayName = "No. of Guarantee Periods - Option",
              dataType = FieldDataType.STRING,
              requirement = FieldRequirement.MANDATORY,
              enumOptions = listOf("Required", "Not Required", "Optional"),
          ),
          field(
              key = "no_of_guarantee_periods_in_email_conf",
              category = CATEGORY_MARKET_AND_TECHNICAL,
              displayName = "No. of Guarantee Periods - In email conf",
              dataType = FieldDataType.BOOLEAN,
              requirement = FieldRequirement.OPTIONAL,
              enumOptions = listOf("True", "False"),
          ),
          field(
              key = "no_of_guarantee_periods_bex_logic",
              category = CATEGORY_MARKET_AND_TECHNICAL,
              displayName = "No. of Guarantee Periods - BEX Logic",
              dataType = FieldDataType.STRING,
              requirement = FieldRequirement.MANDATORY,
              enumOptions = listOf("N/A", "Auto-Generate", "Manual Entry", "System Override"),
          ),
          field(
              key = "no_of_guarantee_periods",
              category = CATEGORY_MARKET_AND_TECHNICAL,
              displayName = "No. of Guarantee Periods",
              dataType = FieldDataType.STRING,
              requirement = FieldRequirement.OPTIONAL,
          ),
          field(
              key = "settlement_frequency_option",
              category = CATEGORY_MARKET_AND_TECHNICAL,
              displayName = "Settlement Frequency - Option",
              dataType = FieldDataType.STRING,
              requirement = FieldRequirement.MANDATORY,
              enumOptions = listOf("Required", "Not Required", "Optional"),
          ),
          field(
              key = "settlement_frequency_in_email_conf",
              category = CATEGORY_MARKET_AND_TECHNICAL,
              displayName = "Settlement Frequency - In email conf",
              dataType = FieldDataType.BOOLEAN,
              requirement = FieldRequirement.OPTIONAL,
              enumOptions = listOf("True", "False"),
          ),
          field(
              key = "settlement_frequency_bex_logic",
              category = CATEGORY_MARKET_AND_TECHNICAL,
              displayName = "Settlement Frequency - BEX Logic",
              dataType = FieldDataType.STRING,
              requirement = FieldRequirement.MANDATORY,
              enumOptions = listOf("N/A", "Auto-Generate", "Manual Entry", "System Override"),
          ),
          field(
              key = "settlement_frequency",
              category = CATEGORY_MARKET_AND_TECHNICAL,
              displayName = "Settlement Frequency",
              dataType = FieldDataType.STRING,
              requirement = FieldRequirement.OPTIONAL,
              enumOptions = listOf("Monthly", "Quarterly", "Semi-Annually", "Annually"),
          ),
      )

  val categories: List<String> =
      listOf(
          CATEGORY_COUNTERPARTY_AND_TENOR,
          CATEGORY_MONETARY_AND_SIZE,
          CATEGORY_COUPON_STRUCTURE,
          CATEGORY_BARRIERS_AND_LEVELS,
          CATEGORY_MARKET_AND_TECHNICAL,
      )

  private fun field(
      key: String,
      category: String,
      displayName: String,
      dataType: FieldDataType,
      requirement: FieldRequirement,
      enumOptions: List<String> = emptyList(),
  ): CatalogFieldDefinition =
      CatalogFieldDefinition(
          key = key,
          category = category,
          displayName = displayName,
          dataType = dataType,
          requirement = requirement,
          enumOptions = enumOptions,
          kind = FieldKind.COMMON,
      )
}
