package com.contactfirstio.structuredproducts.catalog

import com.contactfirstio.structuredproducts.data.document.FieldDataType
import com.contactfirstio.structuredproducts.data.document.FieldKind
import com.contactfirstio.structuredproducts.data.document.FieldRequirement

object StandardFieldCatalog {

  const val CATEGORY_INITIAL_SETUP = "Initial Setup"
  const val CATEGORY_PRODUCT_LIFECYCLE = "Product Lifecycle"
  const val CATEGORY_ISSUER_AND_MARKET = "Issuer & Market"
  const val CATEGORY_PRICING_AND_EXECUTION = "Pricing & Execution"
  const val CATEGORY_IDENTIFIERS_AND_REGULATORY = "Identifiers & Regulatory"
  const val CATEGORY_RETRO_AND_PRR = "Retro & PRR"
  const val CATEGORY_UNDERLYING = "Underlying"
  const val CATEGORY_BARRIER = "Barrier"
  const val CATEGORY_COUPON = "Coupon"

  /** Display order for Product Lifecycle fields in the template fixed values form. */
  val productLifecycleFixedValueFieldOrder: List<String> =
      listOf(
          "available_for_reverse_enquiry",
          "eln_family_flag",
          "cross_price",
          "laf_relevant",
          "investment_amount",
          "pay_off",
          "brochure_link",
          "brochure_attachments",
          "effective_from",
          "effective_to",
      )

  val fields: List<CatalogFieldDefinition> =
      listOf(
          field(
              key = "booking_center",
              category = CATEGORY_INITIAL_SETUP,
              displayName = "Booking Center",
              dataType = FieldDataType.STRING,
              requirement = FieldRequirement.MANDATORY,
              enumOptions = listOf("AU", "HK/SG"),
              defaultedInTemplateCreation = true,
          ),
          field(
              key = "product_type_id",
              category = CATEGORY_INITIAL_SETUP,
              displayName = "Product Type ID",
              dataType = FieldDataType.STRING,
              requirement = FieldRequirement.MANDATORY,
          ),
          field(
              key = "product_name",
              category = CATEGORY_INITIAL_SETUP,
              displayName = "Product Name",
              dataType = FieldDataType.STRING,
              requirement = FieldRequirement.MANDATORY,
          ),
          field(
              key = "risk_profile",
              category = CATEGORY_INITIAL_SETUP,
              displayName = "Risk Profile",
              dataType = FieldDataType.STRING,
              requirement = FieldRequirement.OPTIONAL,
              enumOptions = listOf("Leveraged", "Optimisation", "Performance", "Protection"),
              defaultedInTemplateCreation = true,
          ),
          field(
              key = "pip_id",
              category = CATEGORY_INITIAL_SETUP,
              displayName = "PIP ID",
              dataType = FieldDataType.STRING,
              requirement = FieldRequirement.OPTIONAL,
              defaultedInTemplateCreation = true,
          ),
          field(
              key = "product_idea",
              category = CATEGORY_PRODUCT_LIFECYCLE,
              displayName = "Product Idea",
              dataType = FieldDataType.STRING,
              requirement = FieldRequirement.OPTIONAL,
              enumOptions = listOf("Reverse Enquiry", "New Issue"),
              defaultedInTemplateCreation = true,
              excludedFromFixedValuesOnly = true,
          ),
          field(
              key = "available_for_reverse_enquiry",
              category = CATEGORY_PRODUCT_LIFECYCLE,
              displayName = "Available for Reverse Enquiry",
              dataType = FieldDataType.BOOLEAN,
              requirement = FieldRequirement.OPTIONAL,
              enumOptions = listOf("Yes", "No"),
              defaultedInTemplateCreation = true,
          ),
          field(
              key = "eln_family_flag",
              category = CATEGORY_PRODUCT_LIFECYCLE,
              displayName = "ELN Family Flag",
              dataType = FieldDataType.BOOLEAN,
              requirement = FieldRequirement.OPTIONAL,
              enumOptions = listOf("Yes", "No"),
              defaultedInTemplateCreation = true,
          ),
          field(
              key = "cross_price",
              category = CATEGORY_PRODUCT_LIFECYCLE,
              displayName = "Cross Price",
              dataType = FieldDataType.BOOLEAN,
              requirement = FieldRequirement.OPTIONAL,
              enumOptions = listOf("Yes", "No"),
              defaultedInTemplateCreation = true,
          ),
          field(
              key = "laf_relevant",
              category = CATEGORY_PRODUCT_LIFECYCLE,
              displayName = "LAF Relevant",
              dataType = FieldDataType.BOOLEAN,
              requirement = FieldRequirement.OPTIONAL,
              enumOptions = listOf("Yes", "No"),
              defaultedInTemplateCreation = true,
          ),
          field(
              key = "valid_till",
              category = CATEGORY_PRODUCT_LIFECYCLE,
              displayName = "Valid Till",
              dataType = FieldDataType.DATE,
              requirement = FieldRequirement.OPTIONAL,
              defaultedInTemplateCreation = true,
              excludedFromFixedValuesOnly = true,
          ),
          field(
              key = "effective_from",
              category = CATEGORY_PRODUCT_LIFECYCLE,
              displayName = "Effective From",
              dataType = FieldDataType.DATE,
              requirement = FieldRequirement.OPTIONAL,
              defaultedInTemplateCreation = true,
          ),
          field(
              key = "effective_to",
              category = CATEGORY_PRODUCT_LIFECYCLE,
              displayName = "Effective To",
              dataType = FieldDataType.DATE,
              requirement = FieldRequirement.OPTIONAL,
              defaultedInTemplateCreation = true,
          ),
          field(
              key = "brochure_link",
              category = CATEGORY_PRODUCT_LIFECYCLE,
              displayName = "Brochure Link",
              dataType = FieldDataType.STRING,
              requirement = FieldRequirement.OPTIONAL,
              defaultedInTemplateCreation = true,
          ),
          field(
              key = "brochure_attachments",
              category = CATEGORY_PRODUCT_LIFECYCLE,
              displayName = "Brochure Attachments",
              dataType = FieldDataType.FILE_LIST,
              requirement = FieldRequirement.OPTIONAL,
              defaultedInTemplateCreation = true,
          ),
          field(
              key = "pay_off",
              category = CATEGORY_PRODUCT_LIFECYCLE,
              displayName = "Pay Off",
              dataType = FieldDataType.STRING,
              requirement = FieldRequirement.OPTIONAL,
              defaultedInTemplateCreation = true,
          ),
          field(
              key = "product_creator",
              category = CATEGORY_PRODUCT_LIFECYCLE,
              displayName = "Product Creator",
              dataType = FieldDataType.STRING,
              requirement = FieldRequirement.MANDATORY,
              systemManagedAtProductCreation = true,
          ),
          field(
              key = "creation_timestamp",
              category = CATEGORY_PRODUCT_LIFECYCLE,
              displayName = "Creation Timestamp",
              dataType = FieldDataType.DATETIME,
              requirement = FieldRequirement.MANDATORY,
              systemManagedAtProductCreation = true,
          ),
          field(
              key = "product_status",
              category = CATEGORY_PRODUCT_LIFECYCLE,
              displayName = "Product Status",
              dataType = FieldDataType.STRING,
              requirement = FieldRequirement.MANDATORY,
              enumOptions = listOf("Draft", "Launched", "Archived"),
              defaultedInTemplateCreation = true,
              excludedFromFixedValuesOnly = true,
          ),
          field(
              key = "first_tranche_product_id",
              category = CATEGORY_PRODUCT_LIFECYCLE,
              displayName = "First Tranche Product ID",
              dataType = FieldDataType.STRING,
              requirement = FieldRequirement.OPTIONAL,
          ),
          field(
              key = "denomination",
              category = CATEGORY_PRODUCT_LIFECYCLE,
              displayName = "Denomination",
              dataType = FieldDataType.DOUBLE,
              requirement = FieldRequirement.OPTIONAL,
          ),
          field(
              key = "investment_amount",
              category = CATEGORY_PRODUCT_LIFECYCLE,
              displayName = "Investment Amount",
              dataType = FieldDataType.CHECKBOX_GROUP,
              requirement = FieldRequirement.OPTIONAL,
              enumOptions = listOf("Notional", "Client Proceed"),
              defaultedInTemplateCreation = true,
          ),
          field(
              key = "topmost_issuer_entity",
              category = CATEGORY_PRODUCT_LIFECYCLE,
              displayName = "Topmost Issuer Entity",
              dataType = FieldDataType.STRING,
              requirement = FieldRequirement.OPTIONAL,
          ),
          field(
              key = "market_segment",
              category = CATEGORY_ISSUER_AND_MARKET,
              displayName = "Market Segment",
              dataType = FieldDataType.STRING,
              requirement = FieldRequirement.MANDATORY,
              enumOptions = listOf("Public", "Private", "Institutional"),
              defaultedInTemplateCreation = true,
              excludedFromFixedValuesOnly = true,
          ),
          field(
              key = "ips_product_manager",
              category = CATEGORY_ISSUER_AND_MARKET,
              displayName = "IPS Product Manager",
              dataType = FieldDataType.STRING,
              requirement = FieldRequirement.OPTIONAL,
          ),
          field(
              key = "issuer_guarantor_legal_name",
              category = CATEGORY_ISSUER_AND_MARKET,
              displayName = "Issuer/Guarantor Legal Name",
              dataType = FieldDataType.STRING,
              requirement = FieldRequirement.MANDATORY,
          ),
          field(
              key = "issuer_selection",
              category = CATEGORY_ISSUER_AND_MARKET,
              displayName = "Issuer Selection",
              dataType = FieldDataType.STRING,
              requirement = FieldRequirement.MANDATORY,
              enumOptions =
                  listOf(
                      "BNP Paribas",
                      "Barclays",
                      "Citigroup",
                      "Credit Suisse",
                      "Goldman Sachs",
                      "HSBC",
                      "JPMorgan",
                      "Morgan Stanley",
                      "UBS",
                  ),
          ),
          field(
              key = "price_discovery_log",
              category = CATEGORY_PRICING_AND_EXECUTION,
              displayName = "Price Discovery Log",
              dataType = FieldDataType.STRING,
              requirement = FieldRequirement.OPTIONAL,
          ),
          field(
              key = "itm_settlement_type",
              category = CATEGORY_PRICING_AND_EXECUTION,
              displayName = "ITM Settlement Type",
              dataType = FieldDataType.STRING,
              requirement = FieldRequirement.MANDATORY,
              enumOptions = listOf("Physical", "Cash"),
              defaultedInTemplateCreation = true,
              excludedFromFixedValuesOnly = true,
          ),
          field(
              key = "client_specified_product_provider",
              category = CATEGORY_PRICING_AND_EXECUTION,
              displayName = "Client Specified Product Provider",
              dataType = FieldDataType.BOOLEAN,
              requirement = FieldRequirement.OPTIONAL,
              enumOptions = listOf("Yes", "No"),
          ),
          field(
              key = "best_quote",
              category = CATEGORY_PRICING_AND_EXECUTION,
              displayName = "Best Quote",
              dataType = FieldDataType.BOOLEAN,
              requirement = FieldRequirement.OPTIONAL,
              enumOptions = listOf("Yes", "No"),
          ),
          field(
              key = "other_considerations",
              category = CATEGORY_PRICING_AND_EXECUTION,
              displayName = "Other Considerations",
              dataType = FieldDataType.STRING,
              requirement = FieldRequirement.OPTIONAL,
          ),
          field(
              key = "isin",
              category = CATEGORY_IDENTIFIERS_AND_REGULATORY,
              displayName = "ISIN",
              dataType = FieldDataType.STRING,
              requirement = FieldRequirement.OPTIONAL,
          ),
          field(
              key = "valor",
              category = CATEGORY_IDENTIFIERS_AND_REGULATORY,
              displayName = "Valor",
              dataType = FieldDataType.STRING,
              requirement = FieldRequirement.OPTIONAL,
          ),
          field(
              key = "internal_valor",
              category = CATEGORY_IDENTIFIERS_AND_REGULATORY,
              displayName = "Internal Valor",
              dataType = FieldDataType.STRING,
              requirement = FieldRequirement.OPTIONAL,
          ),
          field(
              key = "starr_id",
              category = CATEGORY_IDENTIFIERS_AND_REGULATORY,
              displayName = "StaRR ID",
              dataType = FieldDataType.STRING,
              requirement = FieldRequirement.OPTIONAL,
          ),
          field(
              key = "rba",
              category = CATEGORY_IDENTIFIERS_AND_REGULATORY,
              displayName = "RBA",
              dataType = FieldDataType.BOOLEAN,
              requirement = FieldRequirement.OPTIONAL,
              enumOptions = listOf("Yes", "No"),
          ),
          field(
              key = "csp",
              category = CATEGORY_IDENTIFIERS_AND_REGULATORY,
              displayName = "CSP",
              dataType = FieldDataType.BOOLEAN,
              requirement = FieldRequirement.OPTIONAL,
              enumOptions = listOf("Yes", "No"),
          ),
          field(
              key = "cops_screen",
              category = CATEGORY_IDENTIFIERS_AND_REGULATORY,
              displayName = "COPS Screen",
              dataType = FieldDataType.STRING,
              requirement = FieldRequirement.OPTIONAL,
          ),
          field(
              key = "security_type",
              category = CATEGORY_IDENTIFIERS_AND_REGULATORY,
              displayName = "Security Type",
              dataType = FieldDataType.STRING,
              requirement = FieldRequirement.OPTIONAL,
          ),
          field(
              key = "apc_code",
              category = CATEGORY_IDENTIFIERS_AND_REGULATORY,
              displayName = "APC Code",
              dataType = FieldDataType.STRING,
              requirement = FieldRequirement.OPTIONAL,
              defaultedInTemplateCreation = true,
          ),
          field(
              key = "retro_fee_bps",
              category = CATEGORY_RETRO_AND_PRR,
              displayName = "Retro Fee(bps)",
              dataType = FieldDataType.DOUBLE,
              requirement = FieldRequirement.OPTIONAL,
          ),
          field(
              key = "retro_frequency",
              category = CATEGORY_RETRO_AND_PRR,
              displayName = "Retro Frequency",
              dataType = FieldDataType.STRING,
              requirement = FieldRequirement.OPTIONAL,
              enumOptions = listOf("Annually", "Semi-Annually"),
          ),
          field(
              key = "indicative_prr",
              category = CATEGORY_RETRO_AND_PRR,
              displayName = "Indicative PRR",
              dataType = FieldDataType.DOUBLE,
              requirement = FieldRequirement.OPTIONAL,
          ),
          field(
              key = "indicative_prr_non_margin",
              category = CATEGORY_RETRO_AND_PRR,
              displayName = "Indicative PRR(Non-Margin)",
              dataType = FieldDataType.DOUBLE,
              requirement = FieldRequirement.OPTIONAL,
          ),
          field(
              key = "prr_non_margin",
              category = CATEGORY_RETRO_AND_PRR,
              displayName = "PRR(Non-Margin)",
              dataType = FieldDataType.DOUBLE,
              requirement = FieldRequirement.OPTIONAL,
          ),
          field(
              key = "underlying_asset",
              category = CATEGORY_UNDERLYING,
              displayName = "Underlying Asset",
              dataType = FieldDataType.STRING,
              requirement = FieldRequirement.MANDATORY,
          ),
          field(
              key = "strike_level",
              category = CATEGORY_UNDERLYING,
              displayName = "Strike Level",
              dataType = FieldDataType.DOUBLE,
              requirement = FieldRequirement.OPTIONAL,
          ),
          field(
              key = "barrier_type",
              category = CATEGORY_BARRIER,
              displayName = "Barrier Type",
              dataType = FieldDataType.STRING,
              requirement = FieldRequirement.MANDATORY,
              enumOptions = listOf("European", "American", "Daily"),
          ),
          field(
              key = "barrier_level",
              category = CATEGORY_BARRIER,
              displayName = "Barrier Level",
              dataType = FieldDataType.DOUBLE,
              requirement = FieldRequirement.OPTIONAL,
          ),
          field(
              key = "coupon_rate",
              category = CATEGORY_COUPON,
              displayName = "Coupon Rate",
              dataType = FieldDataType.DOUBLE,
              requirement = FieldRequirement.OPTIONAL,
          ),
          field(
              key = "autocall_trigger",
              category = CATEGORY_COUPON,
              displayName = "Autocall Trigger",
              dataType = FieldDataType.DOUBLE,
              requirement = FieldRequirement.OPTIONAL,
          ),
      )

  val categories: List<String> =
      listOf(
          CATEGORY_INITIAL_SETUP,
          CATEGORY_PRODUCT_LIFECYCLE,
          CATEGORY_ISSUER_AND_MARKET,
          CATEGORY_PRICING_AND_EXECUTION,
          CATEGORY_IDENTIFIERS_AND_REGULATORY,
          CATEGORY_RETRO_AND_PRR,
          CATEGORY_UNDERLYING,
          CATEGORY_BARRIER,
          CATEGORY_COUPON,
      )

  private fun field(
      key: String,
      category: String,
      displayName: String,
      dataType: FieldDataType,
      requirement: FieldRequirement,
      enumOptions: List<String> = emptyList(),
      defaultedInTemplateCreation: Boolean = false,
      excludedFromFixedValuesOnly: Boolean = false,
      systemManagedAtProductCreation: Boolean = false,
  ): CatalogFieldDefinition =
      CatalogFieldDefinition(
          key = key,
          category = category,
          displayName = displayName,
          dataType = dataType,
          requirement = requirement,
          enumOptions = enumOptions,
          defaultedInTemplateCreation = defaultedInTemplateCreation,
          excludedFromFixedValuesOnly = excludedFromFixedValuesOnly,
          systemManagedAtProductCreation = systemManagedAtProductCreation,
          kind = FieldKind.STANDARD,
      )
}
